name = "personal-portfolio-website"
compatibility_date = "2025-08-13"

[build]
command = "npm run build"

[build.environment_variables]
NODE_VERSION = "18.20.8"

[assets]
directory = "./dist"
not_found_handling = "404-page"